const menu = [
    {
      id: 1,
      title: 'Try Me',
      category: 'The Weeknd',
      price: "My Dear Melancholy",
      img: 'images/dear-melancholy.jpg',
      desc: `"Try me" is a song where the lyrics are pretty interesting and emotionally complex, but it is its production and the little details that take it from good to great: the electric synths, the beats, the vocals throughout, not to mention the ridiculously catchy chorus.`,
      youtubelink:"https://www.youtube.com/watch?v=2DjM0lY4pbE",
    },
    {
      id: 2,
      title: 'Tears Of Gold',
      category: 'Faouzia',
      price: "",
      img: 'images/tears-of-gold.jpg',
      desc: `"Tears Of Gold" represents an emotional pain that Faouzia had in some friendships, where she's been just giving and giving, and nothing was ever reciprocated. On the whole 'Tears of Gold' thing, she was crying for her friends, craying for the platinum love she gave them - not any kind of love.`,
      youtubelink:"https://www.youtube.com/watch?v=XszK-TDzMnQ",
    },
    {
      id: 3,
      title: 'Born Without A Heart',
      category: 'Faouzia',
      price: "",
      img: 'images/born-without-a-heart.jpg',
      desc: `"Born Without A Heart" speaks about Faouzia being hurt too many times by some people to the point where she feels heartless anytime she sees them cry. She cries out in the chorus "I wasn't always like this", and I think that means she has been broken to the point where she feels numb.`,
      youtubelink:"https://www.youtube.com/watch?v=NWivv9nWmSI",
    },
    {
      id: 14,
      title: 'Faith',
      category: 'The Weeknd',
      price: "After Hours",
      img: 'images/after-hours.jpg',
      desc: `"Faith" is mostly centered on The Weeknd losing his faith in pretty much everything. He was slipping back to his dark side for a whole year. But, at this moment, he is reverting back to his “old ways” - pulling himself together.`,
      youtubelink:"https://www.youtube.com/watch?v=8xH0sdjMINY",
    },
    {
      id: 4,
      title: 'Just Like You',
      category: 'NF',
      price: "THE CLOUDS",
      img: 'images/nf-just-like-you.jpg',
      desc: `I believe the overall message of the song is that you are not alone no matter how alone you feel and there are "millions of us just like you" I am one of them so this song cut deep the message is also tell someone you love them because tomorrow isn't promised "Just in case my car goes off the highway or the plane that i get on decides that its my last day".`,
      youtubelink:"https://www.youtube.com/watch?v=A_y_6a5DG4I",
    },
    {
      id: 5,
      title: "I'm Still Here",
      category: 'Sia',
      price: "Monkey Puzzle",
      img: 'images/still-here.jpg',
      desc: `"I’m Still Here" is a victory cry, It speaks of how Sia's past keeps tormenting her and dragging her down, but she continues her good fight no matter how bad she's feeling and she is emerging victorious.`,
      youtubelink:"https://www.youtube.com/watch?v=Jrgbjk45lFA",
    },
    {
      id: 6,
      title: 'Hero',
      category: 'Faouzia',
      price: "",
      img: 'images/Hero.jpg',
      desc: `Thematically, "Hero" discusses having fair and reasonable expectations from the love you give and receive in a relationship or a friendship. It’s a two-way street and any healthy relationship needs both sides to be supportive of each other.`,
      youtubelink:"https://www.youtube.com/watch?v=2zfTPxaX5ss",
    },
    {
      id: 7,
      title: 'Save Your Tears',
      category: 'The Weeknd',
      price: "After Hours",
      img: 'images/after-hours.jpg',
      desc: `The end of a relationship brings with it moments of reflection, resentment and then, eventually, acceptance. Breakups never get any easier no matter the length of your relationship or how many times you do it. That's all what this song is about.`,
      youtubelink:"https://www.youtube.com/watch?v=XXYlFuWEuKI",
    },
    {
      id: 8,
      title: 'The Search',
      category: 'NF',
      price: "THE SEARCH",
      img: 'images/nf-the-search.jpg',
      desc: `In this song, NF raps about struggles from his past and present, the questions that he asks himself everyday, and mental health. He also talks about how he is searching for himself with all the things that life throws at him. This is his best song by far. `,
      youtubelink:"https://www.youtube.com/watch?v=fnlJw9H0xAM",
    },
    {
      id: 11,
      title: 'The Road',
      category: 'Faouzia',
      price:"",
      img: 'images/the-road.jpg',
      desc: `"The Road" is about the bittersweet moments that make you realize you need to move on. It's about taking all your memories and what you've learned and using both to blossom into the next stage of your life.`,
      youtubelink:"https://www.youtube.com/watch?v=oyhFJSaxaW4",
    },
    {
      id: 12,
      title: 'Courage To Change',
      category: 'Sia',
      price: 16.99,
      img: 'images/courage-to-change.jpg',
      desc: `In this song, Sia goes about how she wants her life to be significant while her songs influence people positively. Although she assures her audience throughout the song that together they can achieve several feats, the last line of the verse and the chorus portrays her fear of pursuing change in itself.`,
      youtubelink:"https://www.youtube.com/watch?v=p5QfyF9pkHU",
    },
    {
      id: 17,
      title: 'Dressed In Black',
      category: 'Sia',
      price: "1000 Form Of Fear",
      img: 'images/dressed-in-black.png',
      desc: `"Dressed In Black" isn’t about being found by a person. It was about being discovering music and how it elevated Sia beyond her sadness and sorrow, and how it validated all her tears and pain. It gave her the ability to express her struggles and to turn them into works of art. It was about her learning the power of her voice when she thought her life was worthless.`,
      youtubelink:"https://www.youtube.com/watch?v=1L_6hLmRSQE",
    },
    {
      id: 18,
      title: "You Don't Even Know Me",
      category: 'Faouzia',
      price: "",
      img: 'images/you-dont-even-know-me.jpg',
      desc: `“You Don’t Even Know Me” is a powerful song about being true to yourself no matter what is thrown at you. Nobody knows the real you and what you have been through, except you. So, don’t let anyone tell you what you should be doing. Only you have the right and the power to make decisions about your life.`,
      youtubelink:"https://www.youtube.com/watch?v=C8FTmfZzwP4",
    },
    {
      id: 13,
      title: 'Alive',
      category: 'Sia',
      price: "",
      img: 'images/alive.jpg',
      desc: `"Alive" is definitely one of the most amazing and emotional songs. Simply put, it speaks of life, opening our minds up to a very important distinction: simply surviving the hardships isn’t the same as truly living.`,
      youtubelink:"https://www.youtube.com/watch?v=t2NgsJrrAyM",
    },
    {
      id: 15,
      title: 'False Alarm',
      category: 'The Weeknd',
      price: "Starboy",
      img: 'images/false-alarm.jpg',
      desc: `"False Alarm" speaks about a woman who seems to be struggling with a fear of commitment, a woman who always leaves the man she actually loves. She feels like she can't commit, so she just thinks about commitment, almost as if she wishes she wanted to commit.`,
      youtubelink:"https://www.youtube.com/watch?v=CW5oGRx9CLM",
    },
    {
      id: 10,
      title: 'Shameless',
      category: 'The Weeknd',
      price: "The Beauty Behind The Madness",
      img: 'images/beauty-behind-the-madness.jpg',
      desc: `"Shameless"talks about a girl who is sad, scared to be in a meaningful relationship with someone who cares and loves her, so she has a relationship with The Weeknd, knowing that he doesn't love her, but because he's always there, even if it's just temporary, it temporarily makes her feel cared about, but afterwards, the reality is he's not in love with her.`,
      youtubelink:"https://www.youtube.com/watch?v=uHNS-WbZdLA",
    },
    {
      id: 16,
      title: 'This Mountain',
      category: 'Faouzia',
      price: "",
      img: 'images/this-mountain.jpg',
      desc: `"This mountain" is all about falling down and getting back up. Faouzia wrote this song when people doubted her and kept telling her that she will never make her dreams true, she wrote to encourage herself as well as others.`,
      youtubelink:"https://www.youtube.com/watch?v=hw8MegWR24Q",
    },
    {
      id: 9,
      title: 'Call Out My Name',
      category: 'The Weeknd',
      price: "My Dear Melancholy",
      img: 'images/dear-melancholy.jpg',
      desc: `In this song, The Weeknd focuses on themes of pain, struggle and relationships. He goes in depth on his struggle to let go of this past relationship. He also makes evident that his past lover did not put as much effort into the relationship that he did, wishing that he was still wanted by them.`,
      youtubelink:"https://www.youtube.com/watch?v=M4ZoCHID9GI",
    },
  ];
  export default menu;